# Generated by Django 5.0.4 on 2025-02-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='ProductFeachers',
            new_name='ProductFeature',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='shop_image_created_9f3f47_idx',
            old_name='shop_images_created_e141a2_idx',
        ),
    ]
