# Generated by Django 5.0.4 on 2025-03-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_images_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFeature',
            new_name='ProductFeatures',
        ),
    ]
